<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <AssemblyName>LD51</AssemblyName>
    <OutputPath>Binaries\</OutputPath>
    <IntermediateOutputPath>Intermediates\</IntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source\LevelReader.cs" />
    <Compile Include="Source\LevelSection.cs" />
    <Compile Include="Source\LevelManager.cs" />
    <Compile Include="Source\Vector3Int.cs" />
    <Compile Include="Source\PlayerBase.cs" />
    <Compile Include="Source\Player.cs" />
    <Compile Include="Source\PlayerReplicator.cs" />
    <Compile Include="Source\TimeManager.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Hazel-ScriptCore\Hazel-ScriptCore.csproj" />
    <ProjectReference Include="..\..\..\..\vendor\Coral\Coral.Managed\Coral.Managed-Static.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>
</Project>
