<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <RootNamespace>Hazel</RootNamespace>
    <AssemblyName>Hazel-ScriptCore</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source\Hazel\Attributes\EditorAssignableAttribute.cs" />
    <Compile Include="Source\Hazel\Attributes\ShowInEditorAttribute.cs" />
    <Compile Include="Source\Hazel\Core\FormatUtils.cs" />
    <Compile Include="Source\Hazel\Core\Input.cs" />
    <Compile Include="Source\Hazel\Core\InternalCalls.cs" />
    <Compile Include="Source\Hazel\Core\Log.cs" />
    <Compile Include="Source\Hazel\Math\Vector2.cs" />
    <Compile Include="Source\Hazel\Math\Vector3.cs" />
    <Compile Include="Source\Hazel\Scene\Components.cs" />
    <Compile Include="Source\Hazel\Scene\Entity.cs" />
    <Compile Include="Source\Hazel\Scene\Scene.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\vendor\Coral\Coral.Managed\Coral.Managed-Static.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
